[package]
name = "hasher"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version = "0.1.0"
readme.workspace = true

[dependencies]
sha3 = "0.10.8"

[lints]
workspace = true
